#!/bin/sh

# If you get this code and you don't have a configure, you can run this
# script to create the build infrastructure.

case `uname` in
    Darwin*) glibtoolize ;;
    *) libtoolize ;;
esac
aclocal
autoconf
automake -a
